.TH HSH 1 "2026-02-11" "0.1" "General Commands Manual"
.SH NAME
hsh \- UNIX command line interpreter
.SH SYNOPSIS
.B hsh
.SH DESCRIPTION
.B hsh
is a sh-compatible command language interpreter that executes commands read from the standard input.
.SH SEE ALSO
.BR sh (1), bash (1)
.SH AUTHOR
Agil Mammadov <mammadovagil@tutamail.com>

